export const FETCH_SENDER = 'FETCH_SENDER';
export const FETCH_RECEIVER = 'FETCH_RECEIVER';
export const USER_IS_TYPING = 'USER_IS_TYPING';
export const USER_STOPPED_TYPING = 'USER_STOPPED_TYPING';
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
